# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b3ebc7e97fdab1ab6b1b65602ec114278d51508aaa095311eff73a115970f31bd491547510d8f130dcee07bb39cb90ad69d368f78f41d75581ce472e842d57e

test:
  secret_key_base: 9d6daa7de03721c182f02ad727d7265103d2e4c5154870e3488cf92a7d4e919026403e12954a1b098b91ca3a0c7ace49f9a718a26423ff1bc8d66bf1356dddad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
